[server]
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#0284C7"
backgroundColor = "#0F172A"
secondaryBackgroundColor = "#1E293B"
textColor = "#F8FAFC"
